# paths
tr_path: data/supervised/train.txt
va_path: data/supervised/dev.txt
te_path: data/supervised/test.txt

# data preparation
max_seq_len: 64   # max number of words in the sentence
max_word_len: 16  # max number of characters in the word
word_support: 10  # min frequency of the word to be included in vocabulary
char_support: 100 # min frequency of the character to be included in vocabulary

# hyperparameters
batch_size: 128
num_epochs: 10
lr: 0.001
reg_lambda: 0.0001
max_grad_norm: 100

# network architeecture
word_embed_size: 128
char_embed_size: 128
kernel_size: 3
rnn_cell: LSTM
rnn_hidden_size: 128
num_layers: 1
dropout: 0.5
skip_connection: False